#pragma once

#define IDM_FILE_EXIT 100
#define IDM_EDIT_COPY 110
#define IDM_VIEW_REFRESH 120
#define IDM_VIEW_STOP 121
#define IDM_SEARCH_FIND 130
#define IDM_BOOKMARK_ADD 140
#define IDM_TOOLS_OPTIONS 150
#define IDM_HELP_ABOUT 160
#define IDM_CHECK_UPDATE 161
#define IDM_SETTINGS_RESET_LAYOUT 162

#define IDC_SEARCH_EDIT 1000
#define IDC_RESULTS_LIST 1001
#define IDC_STATUSBAR 1002
#define IDC_PROGRESS  1003

#define IDT_STATUSBAR_TIMER 2000
#define IDT_SEARCH_DEBOUNCE 2001
#define IDT_SPINNER_ANIM    2002
#define IDT_LIST_RETRY      2003
#define IDI_APP_ICON      10

#define IDI_TRAY_ICON     1         // 托盘图标 ID
#define IDM_TRAY_SHOW     170       // 托盘菜单：显示窗口
#define IDM_TRAY_EXIT     171       // 托盘菜单：退出程序

#define IDM_CTX_OPEN_FOLDER     180  // 右键菜单：打开归档文件所在文件夹
#define IDM_CTX_PROPERTIES      181  // 右键菜单：显示归档文件属性
#define IDM_CTX_COPY_NAME       182  // 右键菜单：复制文件名
#define IDM_CTX_COPY_ENTRY_PATH 183  // 右键菜单：复制条目相对路径
#define IDM_CTX_COPY_ARCHIVE    184  // 右键菜单：复制归档文件路径
#define IDM_CTX_EXTRACT         185  // 右键菜单：解压到自定义目录
#define IDM_CTX_OPEN_ARCHIVE    186  // 右键菜单：打开归档文件

// ── 多语言字符串 ID ──
// 菜单栏
#define IDS_MENU_FILE           2001
#define IDS_MENU_SETTINGS       2008
#define IDS_MENU_HELP           2009
// 菜单项
#define IDS_MENU_FILE_EXIT      2010
#define IDS_MENU_TOOLS_OPTIONS  2016
#define IDS_MENU_HELP_ABOUT     2017
#define IDS_MENU_CHECK_UPDATE   2018
// 托盘菜单
#define IDS_TRAY_SHOW           2020
#define IDS_TRAY_EXIT           2021
// ListView 列头
#define IDS_COL_NAME            2030
#define IDS_COL_ARCHIVE         2031
#define IDS_COL_PATH            2032
#define IDS_COL_COMPRESSED_SIZE 2033
#define IDS_COL_ORIGINAL_SIZE   2034
#define IDS_COL_MODIFIED_TIME   2035
// 排序箭头
#define IDS_SORT_ASC            2040
#define IDS_SORT_DESC           2041
// 状态栏
#define IDS_STATUS_PROCESSING   2050
#define IDS_STATUS_READY        2051
#define IDS_STATUS_FILE_COUNT   2052
#define IDS_STATUS_ARCHIVE_COUNT 2053
#define IDS_STATUS_SCANNING     2054
#define IDS_STATUS_UPDATING_INDEX 2055
#define IDS_STATUS_PARSING      2056
#define IDS_STATUS_REFRESHING_LIST 2057
// 对话框
#define IDS_ABOUT_TITLE         2060
#define IDS_ABOUT_TEXT          2061
#define IDS_ERROR               2062
#define IDS_DBLCLICK_PLACEHOLDER 2063
#define IDS_SETTINGS_TITLE      2064
#define IDS_SETTINGS_SHOW_FULL_ARCHIVE_PATH 2065
#define IDS_SETTINGS_SAVE_FAILED 2066
#define IDS_SETTINGS_REMEMBER_UI_STATE 2067
#define IDS_SETTINGS_RESET_LAYOUT 2068
#define IDS_SETTINGS_FORMATS_TITLE 2069
// 右键菜单
#define IDS_CTX_OPEN_FOLDER     2070
#define IDS_CTX_PROPERTIES      2071
#define IDS_CTX_COPY_NAME       2072
#define IDS_CTX_COPY_ENTRY_PATH 2073
#define IDS_CTX_COPY_ARCHIVE    2074
#define IDS_CTX_EXTRACT         2075
#define IDS_CTX_EXTRACT_OK      2076
#define IDS_CTX_EXTRACT_FAIL    2077
#define IDS_CTX_EXTRACT_TITLE   2078
#define IDS_CTX_OPEN_ARCHIVE    2079
#define IDS_SETTINGS_DEFAULT_FORMATS 2080
#define IDS_SETTINGS_KNOWN_ALIASES 2081
#define IDS_SETTINGS_CUSTOM_FORMATS 2082
#define IDS_SETTINGS_CUSTOM_EXTENSION 2083
#define IDS_SETTINGS_CUSTOM_PARSER 2084
#define IDS_SETTINGS_ADD 2085
#define IDS_SETTINGS_DELETE 2086
#define IDS_SETTINGS_OK 2087
#define IDS_SETTINGS_CANCEL 2088
#define IDS_SETTINGS_INVALID_EXTENSION 2089
#define IDS_SETTINGS_DUPLICATE_EXTENSION 2090
#define IDS_SETTINGS_COL_ENABLED 2091
#define IDS_SETTINGS_COL_EXTENSION 2092
#define IDS_SETTINGS_COL_PARSER 2093
#define IDS_STARTUP_SCAN_TITLE 2094
#define IDS_STARTUP_SCAN_TEXT 2095
#define IDS_STARTUP_SCAN_OK 2096
#define IDS_STARTUP_SCAN_SETTINGS 2097
#define WM_APP_STARTUP_SCAN_PROMPT (WM_APP + 9)

#define WM_APP_ADD_RESULT (WM_APP + 1)
#define WM_APP_INDEX_DONE (WM_APP + 2)
#define WM_APP_DB_REFRESH (WM_APP + 3)
#define WM_APP_UPDATE_STATUSBAR (WM_APP + 4)
#define WM_APP_ROWS_READY (WM_APP + 5)  // 异步加载完成，wParam=0, lParam=AsyncLoadResult*
#define WM_APP_TRAY       (WM_APP + 6)  // 托盘图标回调消息
#define WM_APP_EXTRACT_DONE (WM_APP + 7) // 解压完成，wParam=1成功/0失败，lParam=ExtractResult*
#define WM_APP_PARSE_PROGRESS (WM_APP + 8) // 解析进度，wParam=已完成数，lParam=总数
