#pragma once

#define IDM_FILE_EXIT 100
#define IDM_EDIT_COPY 110
#define IDM_VIEW_REFRESH 120
#define IDM_VIEW_STOP 121
#define IDM_SEARCH_FIND 130
#define IDM_BOOKMARK_ADD 140
#define IDM_TOOLS_OPTIONS 150
#define IDM_HELP_ABOUT 160

#define IDC_SEARCH_EDIT 1000
#define IDC_RESULTS_LIST 1001

#define WM_APP_ADD_RESULT (WM_APP + 1)
#define WM_APP_INDEX_DONE (WM_APP + 2)
#define WM_APP_DB_REFRESH (WM_APP + 3)
